In [29]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd
from datetime import datetime

BASE_URL = "https://www.aitimes.com"
LIST_URL = "https://www.aitimes.com/news/articleList.html?page={}"
HEADERS = {"User-Agent": "Mozilla/5.0"}

def clean_date(date_str):
    try:
        this_year = datetime.now().year
        dt = datetime.strptime(f"{this_year}.{date_str}", "%Y.%m.%d %H:%M")
        return dt.strftime("%Y-%m-%d %H:%M")
    except:
        return None

def get_article_text(detail_url):
    try:
        res = requests.get(detail_url, headers=HEADERS, timeout=10)
        soup = BeautifulSoup(res.text, "html.parser")
        content_div = soup.select_one("#article-view-content-div") or soup.select_one(".view-content")
        return content_div.get_text(strip=True) if content_div else ""
    except Exception as e:
        print(f"[본문 에러] {detail_url} - {e}")
        return ""

data = []
save_interval = 20  # 20페이지마다 임시 저장

for page in range(1, 501):  # 1~500페이지
    print(f"\n▶ 페이지 {page} 수집 중...")
    try:
        res = requests.get(LIST_URL.format(page), headers=HEADERS, timeout=10)
        soup = BeautifulSoup(res.text, "html.parser")
        items = soup.select("ul.type1 > li")

        for item in items:
            a_tag = item.select_one("h4.titles > a")
            date_tag = item.select_one("em.info.dated")

            if not a_tag or not date_tag:
                continue

            title = a_tag.text.strip()
            link = BASE_URL + a_tag['href'].strip()
            date = clean_date(date_tag.text.strip())
            if date is None:
                continue

            content = get_article_text(link)
            if not content:
                continue

            data.append({
                "title": title,
                "content": content,
                "date": date,
                "url": link
            })

            time.sleep(0.5)

    except Exception as e:
        print(f"[페이지 에러] page {page} - {e}")
        time.sleep(3)
        continue

    # 임시 저장
    if page % save_interval == 0:
        df_temp = pd.DataFrame(data)
        df_temp.to_csv(f"checkpoint_page_{page}.csv", index=False)
        print(f"🔸 checkpoint_page_{page}.csv 저장 완료")

    time.sleep(1)

df = pd.DataFrame(data)
df.to_csv("aitimes_articles_full.csv", index=False)
print("\n전체 크롤링 완료: aitimes_articles_full.csv 저장됨")

▶ 페이지 1 수집 중...

▶ 페이지 2 수집 중...

▶ 페이지 3 수집 중...

▶ 페이지 4 수집 중...

▶ 페이지 5 수집 중...

▶ 페이지 6 수집 중...

▶ 페이지 7 수집 중...

▶ 페이지 8 수집 중...

▶ 페이지 9 수집 중...

▶ 페이지 10 수집 중...

▶ 페이지 11 수집 중...

▶ 페이지 12 수집 중...

▶ 페이지 13 수집 중...

▶ 페이지 14 수집 중...

▶ 페이지 15 수집 중...

▶ 페이지 16 수집 중...

▶ 페이지 17 수집 중...

▶ 페이지 18 수집 중...

▶ 페이지 19 수집 중...

▶ 페이지 20 수집 중...
🔸 checkpoint_page_20.csv 저장 완료

▶ 페이지 21 수집 중...

▶ 페이지 22 수집 중...

▶ 페이지 23 수집 중...

▶ 페이지 24 수집 중...

▶ 페이지 25 수집 중...

▶ 페이지 26 수집 중...

▶ 페이지 27 수집 중...

▶ 페이지 28 수집 중...

▶ 페이지 29 수집 중...

▶ 페이지 30 수집 중...

▶ 페이지 31 수집 중...

▶ 페이지 32 수집 중...

▶ 페이지 33 수집 중...

▶ 페이지 34 수집 중...

▶ 페이지 35 수집 중...

▶ 페이지 36 수집 중...

▶ 페이지 37 수집 중...

▶ 페이지 38 수집 중...

▶ 페이지 39 수집 중...

▶ 페이지 40 수집 중...
🔸 checkpoint_page_40.csv 저장 완료

▶ 페이지 41 수집 중...

▶ 페이지 42 수집 중...

▶ 페이지 43 수집 중...

▶ 페이지 44 수집 중...

▶ 페이지 45 수집 중...

▶ 페이지 46 수집 중...

▶ 페이지 47 수집 중...

▶ 페이지 48 수집 중...

▶ 페이지 49 수집 중...

▶ 페이지 50 수집 중...

▶ 페이지 51 수집 중...

▶ 페이지 52 수집 중...

▶ 페이지 53 수집 중...

▶ 페이지 54 수집 중...

▶ 페이지 55 수집 중...

▶ 페이지 56 수집 중...

▶ 페이지 57 수집 중...

▶ 페이지 58 수집 중...

▶ 페이지 59 수집 중...

▶ 페이지 60 수집 중...
🔸 checkpoint_page_60.csv 저장 완료

▶ 페이지 61 수집 중...

▶ 페이지 62 수집 중...

▶ 페이지 63 수집 중...

▶ 페이지 64 수집 중...

▶ 페이지 65 수집 중...

▶ 페이지 66 수집 중...

▶ 페이지 67 수집 중...

▶ 페이지 68 수집 중...

▶ 페이지 69 수집 중...

▶ 페이지 70 수집 중...

▶ 페이지 71 수집 중...

▶ 페이지 72 수집 중...

▶ 페이지 73 수집 중...

▶ 페이지 74 수집 중...

▶ 페이지 75 수집 중...

▶ 페이지 76 수집 중...

▶ 페이지 77 수집 중...

▶ 페이지 78 수집 중...

▶ 페이지 79 수집 중...

▶ 페이지 80 수집 중...
🔸 checkpoint_page_80.csv 저장 완료

▶ 페이지 81 수집 중...

▶ 페이지 82 수집 중...

▶ 페이지 83 수집 중...

▶ 페이지 84 수집 중...

▶ 페이지 85 수집 중...

▶ 페이지 86 수집 중...

▶ 페이지 87 수집 중...

▶ 페이지 88 수집 중...

▶ 페이지 89 수집 중...

▶ 페이지 90 수집 중...

▶ 페이지 91 수집 중...

▶ 페이지 92 수집 중...

▶ 페이지 93 수집 중...

▶ 페이지 94 수집 중...

▶ 페이지 95 수집 중...

▶ 페이지 96 수집 중...

▶ 페이지 97 수집 중...

▶ 페이지 98 수집 중...

▶ 페이지 99 수집 중...

▶ 페이지 100 수집 중...
🔸 checkpoint_page_100.csv 저장 완료

▶ 페이지 101 수집 중...

▶ 페이지 102 수집 중...

▶ 페이지 103 수집 중...

▶ 페이지 104 수집 중...

▶ 페이지 105 수집 중...

▶ 페이지 106 수집 중...

▶ 페이지 107 수집 중...

▶ 페이지 108 수집 중...

▶ 페이지 109 수집 중...

▶ 페이지 110 수집 중...

▶ 페이지 111 수집 중...

▶ 페이지 112 수집 중...

▶ 페이지 113 수집 중...

▶ 페이지 114 수집 중...

▶ 페이지 115 수집 중...

▶ 페이지 116 수집 중...

▶ 페이지 117 수집 중...

▶ 페이지 118 수집 중...

▶ 페이지 119 수집 중...

▶ 페이지 120 수집 중...
🔸 checkpoint_page_120.csv 저장 완료

▶ 페이지 121 수집 중...

▶ 페이지 122 수집 중...

▶ 페이지 123 수집 중...

▶ 페이지 124 수집 중...

▶ 페이지 125 수집 중...

▶ 페이지 126 수집 중...

▶ 페이지 127 수집 중...

▶ 페이지 128 수집 중...

▶ 페이지 129 수집 중...

▶ 페이지 130 수집 중...

▶ 페이지 131 수집 중...

▶ 페이지 132 수집 중...

▶ 페이지 133 수집 중...

▶ 페이지 134 수집 중...

▶ 페이지 135 수집 중...

▶ 페이지 136 수집 중...

▶ 페이지 137 수집 중...

▶ 페이지 138 수집 중...

▶ 페이지 139 수집 중...

▶ 페이지 140 수집 중...
🔸 checkpoint_page_140.csv 저장 완료

▶ 페이지 141 수집 중...

▶ 페이지 142 수집 중...

▶ 페이지 143 수집 중...

▶ 페이지 144 수집 중...

▶ 페이지 145 수집 중...

▶ 페이지 146 수집 중...

▶ 페이지 147 수집 중...

▶ 페이지 148 수집 중...

▶ 페이지 149 수집 중...

▶ 페이지 150 수집 중...

▶ 페이지 151 수집 중...

▶ 페이지 152 수집 중...

▶ 페이지 153 수집 중...

▶ 페이지 154 수집 중...

▶ 페이지 155 수집 중...

▶ 페이지 156 수집 중...

▶ 페이지 157 수집 중...

▶ 페이지 158 수집 중...

▶ 페이지 159 수집 중...

▶ 페이지 160 수집 중...
🔸 checkpoint_page_160.csv 저장 완료

▶ 페이지 161 수집 중...

▶ 페이지 162 수집 중...

▶ 페이지 163 수집 중...

▶ 페이지 164 수집 중...

▶ 페이지 165 수집 중...

▶ 페이지 166 수집 중...

▶ 페이지 167 수집 중...

▶ 페이지 168 수집 중...

▶ 페이지 169 수집 중...

▶ 페이지 170 수집 중...

▶ 페이지 171 수집 중...

▶ 페이지 172 수집 중...

▶ 페이지 173 수집 중...

▶ 페이지 174 수집 중...

▶ 페이지 175 수집 중...

▶ 페이지 176 수집 중...

▶ 페이지 177 수집 중...

▶ 페이지 178 수집 중...

▶ 페이지 179 수집 중...

▶ 페이지 180 수집 중...
🔸 checkpoint_page_180.csv 저장 완료

▶ 페이지 181 수집 중...

▶ 페이지 182 수집 중...

▶ 페이지 183 수집 중...

▶ 페이지 184 수집 중...

▶ 페이지 185 수집 중...

▶ 페이지 186 수집 중...

▶ 페이지 187 수집 중...

▶ 페이지 188 수집 중...

▶ 페이지 189 수집 중...

▶ 페이지 190 수집 중...

▶ 페이지 191 수집 중...

▶ 페이지 192 수집 중...

▶ 페이지 193 수집 중...

▶ 페이지 194 수집 중...

▶ 페이지 195 수집 중...

▶ 페이지 196 수집 중...

▶ 페이지 197 수집 중...

▶ 페이지 198 수집 중...

▶ 페이지 199 수집 중...

▶ 페이지 200 수집 중...
🔸 checkpoint_page_200.csv 저장 완료

▶ 페이지 201 수집 중...

▶ 페이지 202 수집 중...

▶ 페이지 203 수집 중...

▶ 페이지 204 수집 중...

▶ 페이지 205 수집 중...

▶ 페이지 206 수집 중...

▶ 페이지 207 수집 중...

▶ 페이지 208 수집 중...

▶ 페이지 209 수집 중...

▶ 페이지 210 수집 중...

▶ 페이지 211 수집 중...

▶ 페이지 212 수집 중...

▶ 페이지 213 수집 중...

▶ 페이지 214 수집 중...

▶ 페이지 215 수집 중...

▶ 페이지 216 수집 중...

▶ 페이지 217 수집 중...

▶ 페이지 218 수집 중...

▶ 페이지 219 수집 중...

▶ 페이지 220 수집 중...
🔸 checkpoint_page_220.csv 저장 완료

▶ 페이지 221 수집 중...

▶ 페이지 222 수집 중...

▶ 페이지 223 수집 중...

▶ 페이지 224 수집 중...

▶ 페이지 225 수집 중...

▶ 페이지 226 수집 중...

▶ 페이지 227 수집 중...

▶ 페이지 228 수집 중...

▶ 페이지 229 수집 중...

▶ 페이지 230 수집 중...

▶ 페이지 231 수집 중...

▶ 페이지 232 수집 중...

▶ 페이지 233 수집 중...

▶ 페이지 234 수집 중...

▶ 페이지 235 수집 중...

▶ 페이지 236 수집 중...

▶ 페이지 237 수집 중...

▶ 페이지 238 수집 중...

▶ 페이지 239 수집 중...

▶ 페이지 240 수집 중...
🔸 checkpoint_page_240.csv 저장 완료

▶ 페이지 241 수집 중...

▶ 페이지 242 수집 중...

▶ 페이지 243 수집 중...

▶ 페이지 244 수집 중...

▶ 페이지 245 수집 중...

▶ 페이지 246 수집 중...

▶ 페이지 247 수집 중...

▶ 페이지 248 수집 중...

▶ 페이지 249 수집 중...

▶ 페이지 250 수집 중...

▶ 페이지 251 수집 중...

▶ 페이지 252 수집 중...

▶ 페이지 253 수집 중...

▶ 페이지 254 수집 중...

▶ 페이지 255 수집 중...

▶ 페이지 256 수집 중...

▶ 페이지 257 수집 중...

▶ 페이지 258 수집 중...

▶ 페이지 259 수집 중...

▶ 페이지 260 수집 중...
🔸 checkpoint_page_260.csv 저장 완료

▶ 페이지 261 수집 중...

▶ 페이지 262 수집 중...

▶ 페이지 263 수집 중...

▶ 페이지 264 수집 중...

▶ 페이지 265 수집 중...

▶ 페이지 266 수집 중...

▶ 페이지 267 수집 중...

▶ 페이지 268 수집 중...

▶ 페이지 269 수집 중...

▶ 페이지 270 수집 중...

▶ 페이지 271 수집 중...

▶ 페이지 272 수집 중...

▶ 페이지 273 수집 중...

▶ 페이지 274 수집 중...

▶ 페이지 275 수집 중...

▶ 페이지 276 수집 중...

▶ 페이지 277 수집 중...

▶ 페이지 278 수집 중...

▶ 페이지 279 수집 중...

▶ 페이지 280 수집 중...
🔸 checkpoint_page_280.csv 저장 완료

▶ 페이지 281 수집 중...

▶ 페이지 282 수집 중...

▶ 페이지 283 수집 중...

▶ 페이지 284 수집 중...

▶ 페이지 285 수집 중...

▶ 페이지 286 수집 중...

▶ 페이지 287 수집 중...

▶ 페이지 288 수집 중...

▶ 페이지 289 수집 중...

▶ 페이지 290 수집 중...

▶ 페이지 291 수집 중...

▶ 페이지 292 수집 중...

▶ 페이지 293 수집 중...

▶ 페이지 294 수집 중...

▶ 페이지 295 수집 중...

▶ 페이지 296 수집 중...

▶ 페이지 297 수집 중...

▶ 페이지 298 수집 중...

▶ 페이지 299 수집 중...

▶ 페이지 300 수집 중...
🔸 checkpoint_page_300.csv 저장 완료

▶ 페이지 301 수집 중...

▶ 페이지 302 수집 중...

▶ 페이지 303 수집 중...

▶ 페이지 304 수집 중...

▶ 페이지 305 수집 중...

▶ 페이지 306 수집 중...

▶ 페이지 307 수집 중...

▶ 페이지 308 수집 중...

▶ 페이지 309 수집 중...

▶ 페이지 310 수집 중...

▶ 페이지 311 수집 중...

▶ 페이지 312 수집 중...

▶ 페이지 313 수집 중...

▶ 페이지 314 수집 중...

▶ 페이지 315 수집 중...

▶ 페이지 316 수집 중...

▶ 페이지 317 수집 중...

▶ 페이지 318 수집 중...

▶ 페이지 319 수집 중...

▶ 페이지 320 수집 중...
🔸 checkpoint_page_320.csv 저장 완료

▶ 페이지 321 수집 중...

▶ 페이지 322 수집 중...

▶ 페이지 323 수집 중...

▶ 페이지 324 수집 중...

▶ 페이지 325 수집 중...

▶ 페이지 326 수집 중...

▶ 페이지 327 수집 중...

▶ 페이지 328 수집 중...

▶ 페이지 329 수집 중...

▶ 페이지 330 수집 중...

▶ 페이지 331 수집 중...

▶ 페이지 332 수집 중...

▶ 페이지 333 수집 중...

▶ 페이지 334 수집 중...

▶ 페이지 335 수집 중...

▶ 페이지 336 수집 중...

▶ 페이지 337 수집 중...

▶ 페이지 338 수집 중...

▶ 페이지 339 수집 중...

▶ 페이지 340 수집 중...
🔸 checkpoint_page_340.csv 저장 완료

▶ 페이지 341 수집 중...

▶ 페이지 342 수집 중...

▶ 페이지 343 수집 중...

▶ 페이지 344 수집 중...

▶ 페이지 345 수집 중...

▶ 페이지 346 수집 중...

▶ 페이지 347 수집 중...

▶ 페이지 348 수집 중...

▶ 페이지 349 수집 중...

▶ 페이지 350 수집 중...

▶ 페이지 351 수집 중...

▶ 페이지 352 수집 중...

▶ 페이지 353 수집 중...

▶ 페이지 354 수집 중...

▶ 페이지 355 수집 중...

▶ 페이지 356 수집 중...

▶ 페이지 357 수집 중...

▶ 페이지 358 수집 중...

▶ 페이지 359 수집 중...

▶ 페이지 360 수집 중...
🔸 checkpoint_page_360.csv 저장 완료

▶ 페이지 361 수집 중...

▶ 페이지 362 수집 중...

▶ 페이지 363 수집 중...

▶ 페이지 364 수집 중...

▶ 페이지 365 수집 중...

▶ 페이지 366 수집 중...

▶ 페이지 367 수집 중...

▶ 페이지 368 수집 중...

▶ 페이지 369 수집 중...

▶ 페이지 370 수집 중...

▶ 페이지 371 수집 중...

▶ 페이지 372 수집 중...

▶ 페이지 373 수집 중...

▶ 페이지 374 수집 중...

▶ 페이지 375 수집 중...

▶ 페이지 376 수집 중...

▶ 페이지 377 수집 중...

▶ 페이지 378 수집 중...

▶ 페이지 379 수집 중...

▶ 페이지 380 수집 중...
🔸 checkpoint_page_380.csv 저장 완료

▶ 페이지 381 수집 중...

▶ 페이지 382 수집 중...

▶ 페이지 383 수집 중...

▶ 페이지 384 수집 중...

▶ 페이지 385 수집 중...

▶ 페이지 386 수집 중...

▶ 페이지 387 수집 중...

▶ 페이지 388 수집 중...

▶ 페이지 389 수집 중...

▶ 페이지 390 수집 중...

▶ 페이지 391 수집 중...

▶ 페이지 392 수집 중...

▶ 페이지 393 수집 중...

▶ 페이지 394 수집 중...

▶ 페이지 395 수집 중...

▶ 페이지 396 수집 중...

▶ 페이지 397 수집 중...

▶ 페이지 398 수집 중...

▶ 페이지 399 수집 중...

▶ 페이지 400 수집 중...
🔸 checkpoint_page_400.csv 저장 완료

▶ 페이지 401 수집 중...

▶ 페이지 402 수집 중...

▶ 페이지 403 수집 중...

▶ 페이지 404 수집 중...

▶ 페이지 405 수집 중...

▶ 페이지 406 수집 중...

▶ 페이지 407 수집 중...

▶ 페이지 408 수집 중...

▶ 페이지 409 수집 중...

▶ 페이지 410 수집 중...

▶ 페이지 411 수집 중...

▶ 페이지 412 수집 중...

▶ 페이지 413 수집 중...

▶ 페이지 414 수집 중...

▶ 페이지 415 수집 중...

▶ 페이지 416 수집 중...

▶ 페이지 417 수집 중...

▶ 페이지 418 수집 중...

▶ 페이지 419 수집 중...

▶ 페이지 420 수집 중...
🔸 checkpoint_page_420.csv 저장 완료

▶ 페이지 421 수집 중...

▶ 페이지 422 수집 중...

▶ 페이지 423 수집 중...

▶ 페이지 424 수집 중...

▶ 페이지 425 수집 중...

▶ 페이지 426 수집 중...

▶ 페이지 427 수집 중...

▶ 페이지 428 수집 중...

▶ 페이지 429 수집 중...

▶ 페이지 430 수집 중...

▶ 페이지 431 수집 중...

▶ 페이지 432 수집 중...

▶ 페이지 433 수집 중...

▶ 페이지 434 수집 중...

▶ 페이지 435 수집 중...

▶ 페이지 436 수집 중...

▶ 페이지 437 수집 중...

▶ 페이지 438 수집 중...

▶ 페이지 439 수집 중...

▶ 페이지 440 수집 중...
🔸 checkpoint_page_440.csv 저장 완료

▶ 페이지 441 수집 중...

▶ 페이지 442 수집 중...

▶ 페이지 443 수집 중...

▶ 페이지 444 수집 중...

▶ 페이지 445 수집 중...

▶ 페이지 446 수집 중...

▶ 페이지 447 수집 중...

▶ 페이지 448 수집 중...

▶ 페이지 449 수집 중...

▶ 페이지 450 수집 중...

▶ 페이지 451 수집 중...

▶ 페이지 452 수집 중...

▶ 페이지 453 수집 중...

▶ 페이지 454 수집 중...

▶ 페이지 455 수집 중...

▶ 페이지 456 수집 중...

▶ 페이지 457 수집 중...

▶ 페이지 458 수집 중...

▶ 페이지 459 수집 중...

▶ 페이지 460 수집 중...
🔸 checkpoint_page_460.csv 저장 완료

▶ 페이지 461 수집 중...

▶ 페이지 462 수집 중...

▶ 페이지 463 수집 중...

▶ 페이지 464 수집 중...

▶ 페이지 465 수집 중...

▶ 페이지 466 수집 중...

▶ 페이지 467 수집 중...

▶ 페이지 468 수집 중...

▶ 페이지 469 수집 중...

▶ 페이지 470 수집 중...

▶ 페이지 471 수집 중...

▶ 페이지 472 수집 중...

▶ 페이지 473 수집 중...

▶ 페이지 474 수집 중...

▶ 페이지 475 수집 중...

▶ 페이지 476 수집 중...

▶ 페이지 477 수집 중...

▶ 페이지 478 수집 중...

▶ 페이지 479 수집 중...

▶ 페이지 480 수집 중...
🔸 checkpoint_page_480.csv 저장 완료

▶ 페이지 481 수집 중...

▶ 페이지 482 수집 중...

▶ 페이지 483 수집 중...

▶ 페이지 484 수집 중...

▶ 페이지 485 수집 중...

▶ 페이지 486 수집 중...

▶ 페이지 487 수집 중...

▶ 페이지 488 수집 중...

▶ 페이지 489 수집 중...

▶ 페이지 490 수집 중...

▶ 페이지 491 수집 중...

▶ 페이지 492 수집 중...

▶ 페이지 493 수집 중...

▶ 페이지 494 수집 중...

▶ 페이지 495 수집 중...

▶ 페이지 496 수집 중...

▶ 페이지 497 수집 중...

▶ 페이지 498 수집 중...

▶ 페이지 499 수집 중...

▶ 페이지 500 수집 중...
🔸 checkpoint_page_500.csv 저장 완료

전체 크롤링 완료: aitimes_articles_full.csv 저장됨

In [15]:
pip install konlpy

Collecting konlpy
  Using cached konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: JPype1>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from konlpy) (1.5.2)
Requirement already satisfied: lxml>=4.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from konlpy) (5.2.1)
Requirement already satisfied: numpy>=1.6 in /opt/anaconda3/lib/python3.12/site-packages (from konlpy) (1.26.4)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from JPype1>=0.7.0->konlpy) (24.1)
Using cached konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
Installing collected packages: konlpy
Successfully installed konlpy-0.6.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from datetime import datetime, timedelta
from konlpy.tag import Okt
from collections import Counter
import re

df = pd.read_csv("aitimes_articles_full.csv")

df['date'] = pd.to_datetime(df['date'], errors='coerce')
cutoff = datetime.now() - timedelta(days=30)
df_recent = df[df['date'] >= cutoff].dropna(subset=['content'])

def clean_text(text):
    text = re.sub(r"[^가-힣a-zA-Z\s]", " ", text)  # 한글, 영어, 공백만 남기기
    text = re.sub(r"\s+", " ", text)  # 연속 공백 정리
    return text.strip()

df_recent['cleaned'] = df_recent['content'].apply(clean_text)

okt = Okt()
nouns = []

for text in df_recent['cleaned']:
    nouns += okt.nouns(text)

stopwords = set([
 "!","\"","$","%","&","'","(",")","*","+",",","-",".","...","0","1","2","3","4","5","6","7","8","9",";","<","=",">","?","@","\\","^","_","`","|","~","·","—","——","‘","’","“","”","…","、","。","〈","〉","《","》","가","가까스로","가령","각","각각","각자","각종","갖고말하자면","같다","같이","개의치않고","거니와","거바","거의","것","것과 같이","것들","게다가","게우다","겨우","견지에서","결과에 이르다","결국","결론을 낼 수 있다","겸사겸사","고려하면","고로","곧","공동으로","과","과연","관계가 있다","관계없이","관련이 있다","관하여","관한","관해서는","구","구체적으로","구토하다","그","그들","그때","그래","그래도","그래서","그러나","그러니","그러니까","그러면","그러므로","그러한즉","그런 까닭에","그런데","그런즉","그럼","그럼에도 불구하고","그렇게 함으로써","그렇지","그렇지 않다면","그렇지 않으면","그렇지만","그렇지않으면","그리고","그리하여","그만이다","그에 따르는","그위에","그저","그중에서","그치지 않다","근거로","근거하여","기대여","기점으로","기준으로","기타","까닭으로","까악","까지","까지 미치다","까지도","꽈당","끙끙","끼익","나","나머지는","남들","남짓","너","너희","너희들","네","넷","년","논하지 않다","놀라다","누가 알겠는가","누구","다른","다른 방면으로","다만","다섯","다소","다수","다시 말하자면","다시말하면","다음","다음에","다음으로","단지","답다","당신","당장","대로 하다","대하면","대하여","대해 말하자면","대해서","댕그","더구나","더군다나","더라도","더불어","더욱더","더욱이는","도달하다","도착하다","동시에","동안","된바에야","된이상","두번째로","둘","둥둥","뒤따라","뒤이어","든간에","들","등","등등","딩동","따라","따라서","따위","따지지 않다","딱","때","때가 되어","때문에","또","또한","뚝뚝","라 해도","령","로","로 인하여","로부터","로써","륙","를","마음대로","마저","마저도","마치","막론하고","만 못하다","만약","만약에","만은 아니다","만이 아니다","만일","만큼","말하자면","말할것도 없고","매","매번","메쓰겁다","몇","모","모두","무렵","무릎쓰고","무슨","무엇","무엇때문에","물론","및","바꾸어말하면","바꾸어말하자면","바꾸어서 말하면","바꾸어서 한다면","바꿔 말하면","바로","바와같이","밖에 안된다","반대로","반대로 말하자면","반드시","버금","보는데서","보다더","보드득","본대로","봐","봐라","부류의 사람들","부터","불구하고","불문하고","붕붕","비걱거리다","비교적","비길수 없다","비로소","비록","비슷하다","비추어 보아","비하면","뿐만 아니라","뿐만아니라","뿐이다","삐걱","삐걱거리다","사","삼","상대적으로 말하자면","생각한대로","설령","설마","설사","셋","소생","소인","솨","쉿","습니까","습니다","시각","시간","시작하여","시초에","시키다","실로","심지어","아","아니","아니나다를가","아니라면","아니면","아니었다면","아래윗","아무거나","아무도","아야","아울러","아이","아이고","아이구","아이야","아이쿠","아하","아홉","안 그러면","않기 위하여","않기 위해서","알 수 있다","알았어","앗","앞에서","앞의것","야","약간","양자","어","어기여차","어느","어느 년도","어느것","어느곳","어느때","어느쪽","어느해","어디","어때","어떠한","어떤","어떤것","어떤것들","어떻게","어떻해","어이","어째서","어쨋든","어쩔수 없다","어찌","어찌됏든","어찌됏어","어찌하든지","어찌하여","언제","언젠가","얼마","얼마 안 되는 것","얼마간","얼마나","얼마든지","얼마만큼","얼마큼","엉엉","에","에 가서","에 달려 있다","에 대해","에 있다","에 한하다","에게","에서","여","여기","여덟","여러분","여보시오","여부","여섯","여전히","여차","연관되다","연이서","영","영차","옆사람","예","예를 들면","예를 들자면","예컨대","예하면","오","오로지","오르다","오자마자","오직","오호","오히려","와","와 같은 사람들","와르르","와아","왜","왜냐하면","외에도","요만큼","요만한 것","요만한걸","요컨대","우르르","우리","우리들","우선","우에 종합한것과같이","운운","월","위에서 서술한바와같이","위하여","위해서","윙윙","육","으로","으로 인하여","으로서","으로써","을","응","응당","의","의거하여","의지하여","의해","의해되다","의해서","이","이 되다","이 때문에","이 밖에","이 외에","이 정도의","이것","이곳","이때","이라면","이래","이러이러하다","이러한","이런","이럴정도로","이렇게 많은 것","이렇게되면","이렇게말하자면","이렇구나","이로 인하여","이르기까지","이리하여","이만큼","이번","이봐","이상","이어서","이었다","이와 같다","이와 같은","이와 반대로","이와같다면","이외에도","이용하여","이유만으로","이젠","이지만","이쪽","이천구","이천육","이천칠","이천팔","인 듯하다","인젠","일","일것이다","일곱","일단","일때","일반적으로","일지라도","임에 틀림없다","입각하여","입장에서","잇따라","있다","자","자기","자기집","자마자","자신","잠깐","잠시","저","저것","저것만큼","저기","저쪽","저희","전부","전자","전후","점에서 보아","정도에 이르다","제","제각기","제외하고","조금","조차","조차도","졸졸","좀","좋아","좍좍","주룩주룩","주저하지 않고","줄은 몰랏다","줄은모른다","중에서","중의하나","즈음하여","즉","즉시","지든지","지만","지말고","진짜로","쪽으로","차라리","참","참나","첫번째로","쳇","총적으로","총적으로 말하면","총적으로 보면","칠","콸콸","쾅쾅","쿵","타다","타인","탕탕","토하다","통하여","툭","퉤","틈타","팍","팔","퍽","펄렁","하","하게될것이다","하게하다","하겠는가","하고 있다","하고있었다","하곤하였다","하구나","하기 때문에","하기 위하여","하기는한데","하기만 하면","하기보다는","하기에","하나","하느니","하는 김에","하는 편이 낫다","하는것도","하는것만 못하다","하는것이 낫다","하는바","하더라도","하도다","하도록시키다","하도록하다","하든지","하려고하다","하마터면","하면 할수록","하면된다","하면서","하물며","하여금","하여야","하자마자","하지 않는다면","하지 않도록","하지마","하지마라","하지만","하하","한 까닭에","한 이유는","한 후","한다면","한다면 몰라도","한데","한마디","한적이있다","한켠으로는","한항목","할 따름이다","할 생각이다","할 줄 안다","할 지경이다","할 힘이 있다","할때","할만하다","할망정","할뿐","할수있다","할수있어","할줄알다","할지라도","할지언정","함께","해도된다","해도좋다","해봐요","해서는 안된다","해야한다","해요","했어요","향하다","향하여","향해서","허","허걱","허허","헉","헉헉","헐떡헐떡","형식으로 쓰여","혹시","혹은","혼자","훨씬","휘익","휴","흐흐","흥","힘입어","︿","！","＃","＄","％","＆","（","）","＊","＋","，","０","１","２","３","４","５","６","７","８","９","：","；","＜","＞","？","＠","［","］","｛","｜","｝","～","￥"
, '라며', '통해', '기반', '기자','사용', '제공'
])

filtered = [word for word in nouns if len(word) > 1 and word not in stopwords]


counter = Counter(filtered)
top_keywords = counter.most_common(30)


print("최근 한 달간 가장 많이 등장한 키워드 (상위 30개)\n")
for i, (word, freq) in enumerate(top_keywords, 1):
    print(f"{i:2}. {word:<10} {freq}회")

WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by org.jpype.JPypeContext in an unnamed module (file:/opt/anaconda3/envs/goorm/lib/python3.12/site-packages/org.jpype.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

최근 한 달간 가장 많이 등장한 키워드 (상위 30개)

 1. 모델         1112회
 2. 기술         1011회
 3. 데이터        741회
 4. 사진         696회
 5. 기업         694회
 6. 대표         595회
 7. 개발         585회
 8. 오픈         582회
 9. 지능         545회
10. 사용자        495회
11. 기능         481회
12. 활용         473회
13. 인공         463회
14. 구글         445회
15. 에이전트       424회
16. 검색         393회
17. 설명         392회
18. 서비스        385회
19. 미국         370회
20. 공개         336회
21. 플랫폼        335회
22. 솔루션        332회
23. 로봇         330회
24. 연구         308회
25. 문제         308회
26. 시스템        307회
27. 산업         304회
28. 분석         304회
29. 달러         296회
30. 성능         294회

In [15]:
import pandas as pd
from datetime import datetime, timedelta
from konlpy.tag import Okt
from collections import Counter
import re

df = pd.read_csv("/Users/goorm/Downloads/aitimes_articles_full.csv")

df['date'] = pd.to_datetime(df['date'], errors='coerce')


def clean_text(text):
    text = re.sub(r"[^가-힣a-zA-Z\s]", " ", str(text)) 
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df['cleaned'] = df['content'].apply(clean_text)

okt = Okt()
df['nouns'] = df['cleaned'].apply(lambda x: okt.nouns(x))

stopwords = set( ["!","\"","$","%","&","'","(",")","*","+",",","-",".","...","0","1","2","3","4","5","6","7","8","9",";","<","=",">","?","@","\\","^","_","`","|","~","·","—","——","‘","’","“","”","…","、","。","〈","〉","《","》","가","가까스로","가령","각","각각","각자","각종","갖고말하자면","같다","같이","개의치않고","거니와","거바","거의","것","것과 같이","것들","게다가","게우다","겨우","견지에서","결과에 이르다","결국","결론을 낼 수 있다","겸사겸사","고려하면","고로","곧","공동으로","과","과연","관계가 있다","관계없이","관련이 있다","관하여","관한","관해서는","구","구체적으로","구토하다","그","그들","그때","그래","그래도","그래서","그러나","그러니","그러니까","그러면","그러므로","그러한즉","그런 까닭에","그런데","그런즉","그럼","그럼에도 불구하고","그렇게 함으로써","그렇지","그렇지 않다면","그렇지 않으면","그렇지만","그렇지않으면","그리고","그리하여","그만이다","그에 따르는","그위에","그저","그중에서","그치지 않다","근거로","근거하여","기대여","기점으로","기준으로","기타","까닭으로","까악","까지","까지 미치다","까지도","꽈당","끙끙","끼익","나","나머지는","남들","남짓","너","너희","너희들","네","넷","년","논하지 않다","놀라다","누가 알겠는가","누구","다른","다른 방면으로","다만","다섯","다소","다수","다시 말하자면","다시말하면","다음","다음에","다음으로","단지","답다","당신","당장","대로 하다","대하면","대하여","대해 말하자면","대해서","댕그","더구나","더군다나","더라도","더불어","더욱더","더욱이는","도달하다","도착하다","동시에","동안","된바에야","된이상","두번째로","둘","둥둥","뒤따라","뒤이어","든간에","들","등","등등","딩동","따라","따라서","따위","따지지 않다","딱","때","때가 되어","때문에","또","또한","뚝뚝","라 해도","령","로","로 인하여","로부터","로써","륙","를","마음대로","마저","마저도","마치","막론하고","만 못하다","만약","만약에","만은 아니다","만이 아니다","만일","만큼","말하자면","말할것도 없고","매","매번","메쓰겁다","몇","모","모두","무렵","무릎쓰고","무슨","무엇","무엇때문에","물론","및","바꾸어말하면","바꾸어말하자면","바꾸어서 말하면","바꾸어서 한다면","바꿔 말하면","바로","바와같이","밖에 안된다","반대로","반대로 말하자면","반드시","버금","보는데서","보다더","보드득","본대로","봐","봐라","부류의 사람들","부터","불구하고","불문하고","붕붕","비걱거리다","비교적","비길수 없다","비로소","비록","비슷하다","비추어 보아","비하면","뿐만 아니라","뿐만아니라","뿐이다","삐걱","삐걱거리다","사","삼","상대적으로 말하자면","생각한대로","설령","설마","설사","셋","소생","소인","솨","쉿","습니까","습니다","시각","시간","시작하여","시초에","시키다","실로","심지어","아","아니","아니나다를가","아니라면","아니면","아니었다면","아래윗","아무거나","아무도","아야","아울러","아이","아이고","아이구","아이야","아이쿠","아하","아홉","안 그러면","않기 위하여","않기 위해서","알 수 있다","알았어","앗","앞에서","앞의것","야","약간","양자","어","어기여차","어느","어느 년도","어느것","어느곳","어느때","어느쪽","어느해","어디","어때","어떠한","어떤","어떤것","어떤것들","어떻게","어떻해","어이","어째서","어쨋든","어쩔수 없다","어찌","어찌됏든","어찌됏어","어찌하든지","어찌하여","언제","언젠가","얼마","얼마 안 되는 것","얼마간","얼마나","얼마든지","얼마만큼","얼마큼","엉엉","에","에 가서","에 달려 있다","에 대해","에 있다","에 한하다","에게","에서","여","여기","여덟","여러분","여보시오","여부","여섯","여전히","여차","연관되다","연이서","영","영차","옆사람","예","예를 들면","예를 들자면","예컨대","예하면","오","오로지","오르다","오자마자","오직","오호","오히려","와","와 같은 사람들","와르르","와아","왜","왜냐하면","외에도","요만큼","요만한 것","요만한걸","요컨대","우르르","우리","우리들","우선","우에 종합한것과같이","운운","월","위에서 서술한바와같이","위하여","위해서","윙윙","육","으로","으로 인하여","으로서","으로써","을","응","응당","의","의거하여","의지하여","의해","의해되다","의해서","이","이 되다","이 때문에","이 밖에","이 외에","이 정도의","이것","이곳","이때","이라면","이래","이러이러하다","이러한","이런","이럴정도로","이렇게 많은 것","이렇게되면","이렇게말하자면","이렇구나","이로 인하여","이르기까지","이리하여","이만큼","이번","이봐","이상","이어서","이었다","이와 같다","이와 같은","이와 반대로","이와같다면","이외에도","이용하여","이유만으로","이젠","이지만","이쪽","이천구","이천육","이천칠","이천팔","인 듯하다","인젠","일","일것이다","일곱","일단","일때","일반적으로","일지라도","임에 틀림없다","입각하여","입장에서","잇따라","있다","자","자기","자기집","자마자","자신","잠깐","잠시","저","저것","저것만큼","저기","저쪽","저희","전부","전자","전후","점에서 보아","정도에 이르다","제","제각기","제외하고","조금","조차","조차도","졸졸","좀","좋아","좍좍","주룩주룩","주저하지 않고","줄은 몰랏다","줄은모른다","중에서","중의하나","즈음하여","즉","즉시","지든지","지만","지말고","진짜로","쪽으로","차라리","참","참나","첫번째로","쳇","총적으로","총적으로 말하면","총적으로 보면","칠","콸콸","쾅쾅","쿵","타다","타인","탕탕","토하다","통하여","툭","퉤","틈타","팍","팔","퍽","펄렁","하","하게될것이다","하게하다","하겠는가","하고 있다","하고있었다","하곤하였다","하구나","하기 때문에","하기 위하여","하기는한데","하기만 하면","하기보다는","하기에","하나","하느니","하는 김에","하는 편이 낫다","하는것도","하는것만 못하다","하는것이 낫다","하는바","하더라도","하도다","하도록시키다","하도록하다","하든지","하려고하다","하마터면","하면 할수록","하면된다","하면서","하물며","하여금","하여야","하자마자","하지 않는다면","하지 않도록","하지마","하지마라","하지만","하하","한 까닭에","한 이유는","한 후","한다면","한다면 몰라도","한데","한마디","한적이있다","한켠으로는","한항목","할 따름이다","할 생각이다","할 줄 안다","할 지경이다","할 힘이 있다","할때","할만하다","할망정","할뿐","할수있다","할수있어","할줄알다","할지라도","할지언정","함께","해도된다","해도좋다","해봐요","해서는 안된다","해야한다","해요","했어요","향하다","향하여","향해서","허","허걱","허허","헉","헉헉","헐떡헐떡","형식으로 쓰여","혹시","혹은","혼자","훨씬","휘익","휴","흐흐","흥","힘입어","︿","！","＃","＄","％","＆","（","）","＊","＋","，","０","１","２","３","４","５","６","７","８","９","：","；","＜","＞","？","＠","［","］","｛","｜","｝","～","￥"
, '라며', '통해', '기반', '기자','사용', '제공'])
df['nouns_filtered'] = df['nouns'].apply(lambda x: [word for word in x if len(word) > 1 and word not in stopwords])

df['week'] = df['date'].dt.to_period('W').apply(lambda r: r.start_time)

# 주차별 키워드 빈도 집계
weekly_keywords = []

for week, group in df.groupby('week'):
    all_nouns = sum(group['nouns_filtered'], [])
    counter = Counter(all_nouns)
    top_keywords = counter.most_common(10)
    for word, freq in top_keywords:
        weekly_keywords.append({
            'week': week.strftime('%Y-%m-%d'),
            'keyword': word,
            'freq': freq
        })

weekly_keywords = pd.DataFrame(weekly_keywords)

print("주간 키워드 트렌드 (상위 키워드 10개씩)\n")
for week in sorted(weekly_keywords['week'].unique(), reverse=True):
    print(f"\n📅 {week} 주차")
    display(weekly_keywords[weekly_keywords['week'] == week][['keyword', 'freq']].reset_index(drop=True))

주간 키워드 트렌드 (상위 키워드 10개씩)


📅 2025-06-09 주차

  keyword  freq
0      기술   274
1      모델   264
2      기업   202
3      대표   201
4     데이터   198
5     솔루션   190
6      사진   160
7      지능   148
8      로봇   130
9      인공   122

📅 2025-06-02 주차

  keyword  freq
0      모델   252
1      기술   186
2      기업   180
3      사진   141
4      오픈   139
5     데이터   137
6      개발   133
7      지능   126
8      기능   101
9      인공   100

📅 2025-05-26 주차

  keyword  freq
0      기술   266
1      모델   262
2      사진   199
3     데이터   194
4      기업   171
5      개발   160
6      활용   152
7      대표   152
8     사용자   147
9      오픈   146

📅 2025-05-19 주차

  keyword  freq
0      모델   291
1      기술   237
2     데이터   184
3      구글   179
4      사진   173
5      오픈   171
6      대표   159
7      개발   158
8     사용자   149
9      기능   129

📅 2025-05-12 주차

  keyword  freq
0      모델   315
1      기술   277
2      오픈   201
3      기업   188
4      미국   185
5      사진   182
6     데이터   175
7      대표   143
8      구글   138
9      개발   134

📅 2025-05-05 주차

  keyword  freq
0      모델   244
1      오픈   191
2      기술   162
3      기업   155
4      사진   143
5      검색   142
6     데이터   138
7      구글   132
8      개발   123
9      기능   104

📅 2025-04-28 주차

  keyword  freq
0      모델   334
1      오픈   214
2      기술   171
3      사진   165
4     사용자   162
5      기업   151
6      개발   142
7      기능   132
8      추론   128
9      구글   120

📅 2025-04-21 주차

  keyword  freq
0      모델   381
1      기업   237
2      기술   228
3      오픈   200
4     데이터   199
5      사진   186
6      개발   178
7      활용   156
8    에이전트   149
9      대표   137

📅 2025-04-14 주차

  keyword  freq
0      모델   363
1      기술   236
2     데이터   225
3      오픈   223
4      기업   190
5      개발   170
6      사진   168
7      기능   166
8      지능   148
9      대표   139

📅 2025-04-07 주차

  keyword  freq
0      모델   367
1      기술   219
2      오픈   192
3      사진   184
4     데이터   180
5      기업   179
6      대표   142
7     사용자   140
8      기능   136
9      개발   134

📅 2025-03-31 주차

  keyword  freq
0      모델   300
1      오픈   190
2     데이터   189
3      사진   162
4     사용자   140
5      출시   137
6      기업   136
7      기능   131
8      기술   124
9     이미지   106

📅 2025-03-24 주차

  keyword  freq
0      모델   383
1     데이터   228
2      기업   203
3      사진   190
4      기술   187
5      오픈   187
6      개발   163
7      대표   160
8      지능   131
9     서비스   130

📅 2025-03-17 주차

  keyword  freq
0      모델   420
1      오픈   219
2      사진   191
3     데이터   189
4      기술   187
5      개발   171
6      기업   170
7      활용   159
8      기능   153
9      지능   140

📅 2025-03-10 주차

  keyword  freq
0      모델   383
1      기술   200
2      사진   183
3      기업   175
4     데이터   171
5      개발   164
6      활용   159
7      오픈   143
8      대표   137
9     사용자   136

📅 2025-03-03 주차

  keyword  freq
0      모델   289
1      기술   200
2    에이전트   191
3      오픈   190
4      사진   178
5      개발   178
6     데이터   156
7      기업   148
8      대표   140
9     서비스   134

📅 2025-02-24 주차

  keyword  freq
0      모델   411
1      기술   288
2     데이터   226
3      기업   215
4      사진   212
5      오픈   186
6      대표   171
7      개발   169
8      지능   156
9      활용   155

📅 2025-02-17 주차

  keyword  freq
0      모델   396
1     데이터   204
2      기술   203
3      오픈   195
4      기업   175
5      사진   173
6      시크   169
7      개발   161
8     서비스   157
9      대표   141

📅 2025-02-10 주차

  keyword  freq
0      모델   398
1      오픈   304
2      기업   211
3      사진   200
4      기술   200
5      대표   196
6     데이터   190
7      개발   163
8     서비스   149
9      추론   145

📅 2025-02-03 주차

  keyword  freq
0      모델   338
1      시크   306
2      오픈   253
3      기술   209
4      사진   190
5     데이터   166
6     서비스   164
7      기업   163
8      개발   159
9      대표   137

📅 2025-01-27 주차

  keyword  freq
0      모델   341
1      시크   285
2      오픈   185
3      기술   115
4     데이터   110
5      미국   108
6      달러   107
7      추론   106
8      사진   104
9      비용    96

📅 2025-01-20 주차

  keyword  freq
0      오픈   268
1      모델   259
2     데이터   246
3      기술   230
4      사진   204
5      대표   203
6      기업   201
7      지능   176
8      개발   156
9     서비스   151

📅 2025-01-13 주차

  keyword  freq
0      모델   299
1     데이터   252
2      기술   249
3      기업   224
4      사진   205
5     서비스   180
6     사용자   178
7      개발   166
8      미국   164
9      대표   157

📅 2025-01-06 주차

  keyword  freq
0      기술   265
1      모델   258
2      사진   223
3      기업   197
4      대표   197
5      개발   194
6     데이터   175
7     서비스   165
8      활용   142
9      지능   136

📅 2024-12-30 주차

  keyword  freq
0      기술   210
1      대표   198
2      기업   180
3      모델   156
4     서비스   152
5      사진   120
6      개발   108
7      시장   102
8     지난해   100
9     데이터    99